# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cartDetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 764)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connect = QtWidgets.QPushButton(self.centralwidget)
        self.connect.setGeometry(QtCore.QRect(80, 80, 121, 41))
        self.connect.setObjectName("connect")
        self.connInfo = QtWidgets.QLabel(self.centralwidget)
        self.connInfo.setGeometry(QtCore.QRect(30, 670, 171, 20))
        self.connInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.connInfo.setObjectName("connInfo")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(280, 40, 21, 571))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.readRecords = QtWidgets.QPushButton(self.centralwidget)
        self.readRecords.setGeometry(QtCore.QRect(430, 80, 161, 41))
        self.readRecords.setObjectName("readRecords")
        self.print = QtWidgets.QPushButton(self.centralwidget)
        self.print.setGeometry(QtCore.QRect(710, 80, 161, 41))
        self.print.setObjectName("print")
        self.portUsed = QtWidgets.QLabel(self.centralwidget)
        self.portUsed.setGeometry(QtCore.QRect(30, 180, 251, 20))
        self.portUsed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.portUsed.setObjectName("portUsed")
        self.cartName = QtWidgets.QLabel(self.centralwidget)
        self.cartName.setGeometry(QtCore.QRect(30, 310, 251, 20))
        self.cartName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cartName.setObjectName("cartName")
        self.recordDetail = QtWidgets.QTextEdit(self.centralwidget)
        self.recordDetail.setGeometry(QtCore.QRect(390, 160, 521, 531))
        self.recordDetail.setObjectName("recordDetail")
        self.sfVersion = QtWidgets.QLabel(self.centralwidget)
        self.sfVersion.setGeometry(QtCore.QRect(30, 380, 251, 16))
        self.sfVersion.setObjectName("sfVersion")
        self.karsanPartRef = QtWidgets.QLabel(self.centralwidget)
        self.karsanPartRef.setGeometry(QtCore.QRect(30, 450, 251, 16))
        self.karsanPartRef.setObjectName("karsanPartRef")
        self.productID = QtWidgets.QLabel(self.centralwidget)
        self.productID.setGeometry(QtCore.QRect(30, 250, 251, 16))
        self.productID.setObjectName("productID")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connect.setText(_translate("MainWindow", "Connect"))
        self.connInfo.setText(_translate("MainWindow", "Connection status : "))
        self.readRecords.setText(_translate("MainWindow", "Read Records"))
        self.print.setText(_translate("MainWindow", "Export to PDF"))
        self.portUsed.setText(_translate("MainWindow", "Port used : "))
        self.cartName.setText(_translate("MainWindow", "Hardware version : "))
        self.sfVersion.setText(_translate("MainWindow", "Software version :"))
        self.karsanPartRef.setText(_translate("MainWindow", "KARSAN part reference : "))
        self.productID.setText(_translate("MainWindow", "Product ID : "))
